### PR TITLE
Discovery routing 1

### PR DESCRIPTION
**Pull request by vinnnyr**

### CODE REVIEW

**Comment by vinnnyr** [comment]
ugh sorry again. :sweat_smile:

**Comment by JEnoch** [comment]
I'll take this for a strong encouragement to merge my fork quickly! 😆

**Comment by vinnnyr** [comment]
this is what i get for trying to use github web interface to do merges for me. embarrassing public mistakes :joy:  Not sure why it defaults into a PR into the origin

**Comment by JEnoch** [comment]
No problem!
BTW, I just pushed [a fix](https://github.com/JEnoch/zenoh-plugin-dds/commit/4671d81c8383c3ef32038336c971e39f5ec155b0) in my branch that you probably want to pull and test. It stabilises the complete discovery of ROS graph, whatever the startup order of nodes and bridges.
Now it just miss some cleanup when nodes or bridges are leaving. That's for next week...

**Pull request closed without merging**
